---
- name: Updating Security Patches
  hosts: all
  tasks:
    - name: update machine
      shell: |
        if [ \`yum update -y | egrep 'No packages marked for update|Nothing to do' | wc -l\` == 0 ]
        then
          echo 'Yes'
        else
          echo 'No'
        fi
    - name: reboot the server if required
      shell: |
        if [ \`needs-restarting -r | egrep 'Reboot is required' | wc -l\` == 0 ]
        then
          echo 'No'
        else
          echo 'Yes'
          shutdown -r now
        fi
